# Generated by Django 4.1 on 2022-09-02 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petMe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='species',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='petMe.species', unique=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='petMe.user'),
        ),
    ]
