# Generated by Django 4.1 on 2022-09-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petMe', '0002_pet_species_pet_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='species',
            new_name='name',
        ),
    ]
