# Generated by Django 4.1 on 2022-09-06 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petMe', '0003_rename_species_species_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='affection',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pet',
            name='birth_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='health',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='hunger',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='last_play_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='petMe.species', unique=True),
        ),
    ]
