# Generated by Django 4.1 on 2022-09-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petMe', '0005_alter_pet_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
