# Generated by Django 4.1 on 2022-09-07 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('petMe', '0006_pet_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='last_fed_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
