# Generated by Django 4.1 on 2022-09-11 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petMe', '0010_alter_pet_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='petMe.species'),
        ),
    ]
